### ISSUE TITLE
Bug? JUnit tests and classes in Gin jar

### ISSUE THREAD

**Issue by sandybrownlee** [gintool/gin#17]
Ordinarily if there is a bug in the test class, then we get a compile error, and if a test fails, there is a "failed to pass all tests".

In examples/TriangleTest.java, if all references to the Triangle class are replaced with ExampleTriangleProgram, then Gin will run, but reporting much faster run times (one example just now has 1203275 ns for the unpatched program), like the delay code didn't trigger but everything else did.

I assume this is because the JUnit reflection code finds ExampleTriangleProgram in the Gin classpath and runs it, though it doesn't explain why the delay isn't firing. Possibly this is just "something to watch out for"?

**Comment by drdrwhite** [comment]
This is fixed in a private fork and will be release later this year.

**Comment by sandybrownlee** [comment]
Fixed with v2.
