### ISSUE TITLE
features for "patch analyser"

### ISSUE THREAD

**Issue by markuswagnergithub** [gintool/gin#20]
To support the final assessment of the impact of patches, it would be good to provide a bit of help to the users. Most of the following thoughts are around an optional testing phase that happens immediately after the actual optimisation phase (the evolution). This is a bit similar to what is implemented in the automated algorithm configurator irace.

Some random thoughts, in no particular order:
1) For the functional properties (e.g. "number of tests passed"), the final test phase provides an easy-to-use overview. This becomes especially important in case Gin works with more than just a single solution at a time in the future, e.g. by considering trade-offs or populations or multiple solutions that all satisfy the functional requirements are found. As functional tests are typically deterministic in their outcome, no special handling of noise is necessary.
This also applies to measurements of deviation from the oracle (think of a target vector from which the actual calculations of the patched code deviate).
2) However, some measurements are not deterministic: runtime, memory consumption (debatable), energy consumption, ... For these cases, in order to achieve meaningful and trustworthy observations that can be used/published, it would be good if tests can be run repeatedly. In irace, I have to specify this for each test (== problem instance) individually. As tests can vary in the resources needed, we can go this way or simply let the user provide a global setting, e.g., "do 100 repetitions". If Gin does the repetitions, then the individual results should be piped into a CSV file, because you never know what kind of statistical analyses the user wants to run.
3) Statistics: if we do the processing on Gin's end, then we need to decide what statistics to provide. min/max/average/median/stdev/quartiles might be a good start - and already more than what the average user needs. The alternative is to let the user handle this, which is how irace handles it. It does not know anything about repetitions, but just runs the configurations on the provided test instances.
4) Testing & side-effects & plenty of noise: as some tests can be affected by noise and can have side-effects (e.g. due to warming up of the system, due to side-effects, due to dynamic overclocking of single cores, ...), and in case Gin is to do the repetitions, then Gin might have to execute patches A/B/C/D alternatingly, in order to bias the measurements as little as possible and to average out noise: ABCDABCDABCD...
For two patches one might actually want to do ABABAB...BABABA, but it is not clear to me how to extend this to larger sets of patches - therefore the suggested round-robin.

A few of these thoughts have consequences for Gin's internal survival mechanism (read: which solution to pick in case of a local search), but that's a different story...

**Comment by sandybrownlee** [comment]
Point 1, can be handled at the sampler or search level (though it isn't in any of the currently implemented ones)
Point 2, see issue #51.
Point 3, user handles this - results are written out separately for each test repeat.
Point 4, can now specify list of unit tests to run and they'll run in that order.
