### ISSUE TITLE
Incorporate Integration Tests

### ISSUE THREAD

**Issue by drdrwhite** [gintool/gin#26]
The tests in IntegrationTests.java test the dynamic loading of in-memory compiled classes and use java assertions. These need to be turned into proper integration tests. I was unable to get these working with junit, because it interferes with the custom class loading.

So for now, integrating these into cradle to run on "gradle test" would be a good idea.

**Comment by drdrwhite** [comment]
This is done in a private fork and will be released later in 2018.

**Comment by sandybrownlee** [comment]
Fixed in v2.
