### ISSUE TITLE
Test Case for Examples

### ISSUE THREAD

**Issue by drdrwhite** [gintool/gin#3]
We should add a new test case that compiles all the examples in ./examples/ and runs their tests against them.

The examples are excluded from the main source tree to ensure dynamic class loading works correctly, but this also means they're not being properly built and tested.

An alternative would be to have gradle build and test them. Unsure what's best.

**Comment by codykenb** [comment]
Gradle build sounds good to keep the separation, though can we test dynamic
class loading via unit tests? Is gradle generally used to perform an
end-to-end test of a typical GIN run?
