### ISSUE TITLE
Edit fromString methods assume no spaces in filenames

### ISSUE THREAD

**Issue by sandybrownlee** [gintool/gin#34]
These methods typically use spaces to split into tokens for parsing. This split will include any spaces in the source file name.

**Comment by sandybrownlee** [comment]
Might be fixable with lookaheads in the call to split(). Needs investigation. Worst-case, needs a change to the toString() methods.

**Comment by justynapt** [comment]
The 'space' in the filename  issue affects hprof in Profiler. Needs checking.

**Comment by sandybrownlee** [comment]
Fixed. Added quotes to filenames in all Edit.toString() methods, and necessary handling code to all fromString() methods. This should be backwards compatible; if no quotes present fromString should still work.  Have tried adding spaces to paths in hprof tests for simple-gradle and it seemed to work okay still - possibly not a problem there. Closing until we can replicate any further issues with spaces.
