### ISSUE TITLE
Performance issue with the parsing of the method file

### ISSUE THREAD

**Issue by GiovaniGuizzo** [gintool/gin#40]
There is a minor performance issue with the parsing of the method file.
[This block](https://github.com/gintool/gin/blob/a7b868eccc870cd8edea15e2a7d3fd4a97947b74/src/main/java/gin/util/Sampler.java#L358-L360) is not very efficient when we have thousands of test cases.

A HashSet instead of a List solves this problem. I tried to change it, but apparently the method index in this List is used in some classes. The refactoring would change the functionality of such classes, so I decided to create this issue instead.

If I end up fixing this issue, I'll commit the changes.
Cheers,
Giovani.

**Comment by justynapt** [comment]
Pull request accepted, closing. Thank you.
