### ISSUE TITLE
Failure of RTS tests due to uninitiated .ekstazi directory

### ISSUE THREAD

**Issue by justynapt** [gintool/gin#80]
gin.util.regression.impl.EkstaziRTSTest.testConstructor fails as examples/unittests/ekstazi/.ekstazi is not created by Config.createStorer(); - no idea why; need to consult with Giovani, to be resolved later

**Comment by GiovaniGuizzo** [comment]
Issue fixed in [my last commit.](https://github.com/gintool/gin/commit/5840494db81c90ce61536189769249d8ffc9a67d)
