### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by sandybrownlee** [gintool/gin#97]
Run:
`java -jar build/gin.jar -f examples/triangle/Triangle.java -m "classifyTriangle(int,int,int)"`

in a terminal and it now fails.

This seems to be connected with the switch to junit 5.

In JUnitBridge, we have the following:

`Launcher launcher = session.getLauncher();`

`TestPlan testPlan = launcher.discover(request);`

`launcher.execute(testPlan, new TestRunListener(result));`

If I run this using gradle wrapper in a terminal, then calling testPlan.containsTests() here returns false (it's true in eclipse).

**Comment by sandybrownlee** [comment]
Eclipse is picking up the full classpath from the project.

Run like this in a terminal and it works:
```java -cp build/gin.jar:/home/oldchap/.gradle/caches/modules-2/files-2.org.junit.vintage/junit-vintage-engine/5.9.2/53421816bde124a564a64ba005dcc0c8e66a9722/junit-vintage-engine-5.9.2.jar gin.LocalSearch -f examples/triangle/Triangle.java -m "classifyTriangle(int,int,int)```

This is caused by junit vintage being omitted from the jar classpath somehow. Looking for a fix now.

**Comment by sandybrownlee** [comment]
Likewise, build Gin with the copyToLib task:

```./gradlew clean build -x test copyToLib```

Then run like this
```java -cp build/gin.jar:lib/junit-vintage-engine-5.9.2.jar gin.LocalSearch -f examples/triangle/Triangle.java -m "classifyTriangle(int,int,int)"```

**Comment by GiovaniGuizzo** [comment]
Interesting. Perhaps if we explicitly put the version of the jar in `build.gradle` instead of the `implementation platform('org.junit:junit-bom:5.9.2')`, the jar will pick the correct classpath?

**Comment by sandybrownlee** [comment]
Just gave it a try and that has indeed fixed it!

**Comment by GiovaniGuizzo** [comment]
That is indeed a weir bug. I'm glad that fixed it.

**Comment by sandybrownlee** [comment]
Thanks for the suggestion :)
