### ISSUE TITLE
EmptyPatchTester of Full Example with a Maven Project does not work 

### ISSUE THREAD

**Issue by TareqChy1** [gintool/gin#98]
# Help wanted

I was facing an error when trying to execute the EmptyPatchTester command. I provided the error screenshot below.
![Screenshot from 2023-07-12 22-11-16](https://github.com/gintool/gin/assets/72359017/8d054fa6-af52-48cb-9816-62be201a552b)

How can I solve this problem, can anyone provide me any solution?

**Comment by justynapt** [comment]
Resolved via email. Not an issue with Gin. Closing.
